### ISSUE TITLE
https errors

### ISSUE THREAD

**Issue by darkvertex** [chadrien/sublime-toggl#6]
I'm getting a lot of this:

```
Traceback (most recent call last):
  File "toggl.commands.manage_time_entries_window in /mnt/users/alan/.config/sublime-text-3/Installed Packages/Toggl Timer.sublime-package", line 37, in chose_start_option
  File "toggl.commands.base_manage_window in /mnt/users/alan/.config/sublime-text-3/Installed Packages/Toggl Timer.sublime-package", line 16, in retrieve_workspaces
  File "toggl.commands.base_manage_window in /mnt/users/alan/.config/sublime-text-3/Installed Packages/Toggl Timer.sublime-package", line 24, in create_workspace_api_client
  File "toggl.utils.toggl_api.toggl_base_api in /mnt/users/alan/.config/sublime-text-3/Installed Packages/Toggl Timer.sublime-package", line 21, in authenticate
  File "toggl.utils.toggl_api.toggl_base_api in /mnt/users/alan/.config/sublime-text-3/Installed Packages/Toggl Timer.sublime-package", line 40, in request
  File "./urllib/request.py", line 156, in urlopen
  File "./urllib/request.py", line 469, in open
  File "./urllib/request.py", line 492, in _open
  File "./urllib/request.py", line 447, in _call_chain
  File "./urllib/request.py", line 1310, in unknown_open
urllib.error.URLError: <urlopen error unknown url type: https>
```

It might be related to the fact I'm behind a corporate proxy. I didn't see a question in the FAQ about this... How do I tell sublime-toggl to auth API calls with my proxy credentials??

**Comment by chadrien** [comment]
Hi.

Sadly there is no way to do it for now.
Unfortunately I don't use Sublime much anymore, but if you find a solution and would like to share it, don't hesitate to fork and pull request :smiley:

**Comment by darkvertex** [comment]
Bah humbug! Oh well... Thanks for acknowledging. I'll see if I can find some time to edit your connection code to make it work behind a proxy.
